[username]
disabled = true

[hostname]
disabled = true

[directory]
truncate_to_repo = false
fish_style_pwd_dir_length = 1

[git_status]
stashed = ""
conflicted = ""
deleted = ""
staged = ""
modified = ""
untracked = ""

[package]
disabled = true

[nodejs]
disabled = true

[java]
disabled = true
