format= """
$hostname\
$os\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$python\
$line_break\
$custom\
$jobs\
$container\
$shell\
$character"""

[hostname]
ssh_only = true
ssh_symbol = " "
format = "$ssh_symbol"
disabled = false

[directory]
style = "bold blue"
truncate_to_repo = false
fish_style_pwd_dir_length = 1

[git_status]
modified = "!${count}"
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"

[git_branch]
symbol = " "
format = "[$symbol$branch(:$remote_branch)]($style) "

[os]
disabled = false

[os.symbols]
Arch = "󰣇 "
Windows = " "
Macos = " "

[custom.root]
when = 'test "$USER" = "root"'
style = "bold yellow"
format = "[󱐋 ]($style)"

[python]
detect_files = []
symbol = " "
format = '[${symbol}${pyenv_prefix}(${version} )]($style)'

